In [1]:
## ipak function: install multiple R packages, if not already installed
ipak <- function(pkg){
  new.pkg <- pkg[!(pkg %in% installed.packages()[, "Package"])]
  if (length(new.pkg))
    install.packages(new.pkg, dependencies = TRUE)
}

## names of missing columns
nacols <- function(df) {
  colnames(df)[unlist(lapply(df, function(x) anyNA(x)))]
}

In [2]:
### Install and load r packages ====
## specify packages
packages <- c("tidyverse", "caret", "haven", "skimr", "DataExplorer", "GGally", 
              "ggplot2", "psych", "purrr", "dplyr", "data.table", "gvlma", "car", "lavaan", "semPlot")

# install packages
ipak(packages)

# load packages
for (val in packages){
    library(val, character.only = TRUE)
}

-- Attaching packages --------------------------------------- tidyverse 1.2.1 --
v ggplot2 3.2.1     v purrr   0.3.2
v tibble  2.1.3     v dplyr   0.8.3
v tidyr   1.0.0     v stringr 1.4.0
v readr   1.3.1     v forcats 0.4.0
-- Conflicts ------------------------------------------ tidyverse_conflicts() --
x dplyr::filter() masks stats::filter()
x dplyr::lag()    masks stats::lag()
Loading required package: lattice

Attaching package: 'caret'

The following object is masked from 'package:purrr':

    lift


Attaching package: 'skimr'

The following object is masked from 'package:stats':

    filter

Registered S3 method overwritten by 'GGally':
  method from
  +.gg   ggplot2

Attaching package: 'GGally'

The following object is masked from 'package:dplyr':

    nasa


Attaching package: 'psych'

The following objects are masked from 'package:ggplot2':

    %+%, alpha


Attaching package: 'data.table'

The following objects are masked from 'package:dplyr':

    between, first, last

The following object is masked from 'package:purrr':

    transpose

Loading required package: carData

Attaching package: 'car'

The following object is masked from 'package:psych':

    logit

The following object is masked from 'package:dplyr':

    recode

The following object is masked from 'package:purrr':

    some

This is lavaan 0.6-5
lavaan is BETA software! Please report any bugs.

Attaching package: 'lavaan'

The following object is masked from 'package:psych':

    cor2cov

Warning message:
"package 'semPlot' was built under R version 3.6.3"Registered S3 methods overwritten by 'lme4':
  method                          from
  cooks.distance.influence.merMod car
  influence.merMod                car
  dfbeta.influence.merMod         car
  dfbetas.influence.merMod        car
Registered S3 methods overwritten by 'BDgraph':
  method    from
  plot.sim  lava
  print.sim lava
Registered S3 methods overwritten by 'huge':
  method    from
  plot.sim  BDgraph
  print.sim BDgraph

In [3]:
Data_sem <- fread("../data/data.csv")

In [8]:
head(Data_sem)

  ID JS1 OC1 OC2 EP1 OC3 OC4 EP2 EP3 AC1 ... AC3 SI3 AC4 SI4 C1 C2 C3 AGE EXP
1 1  5   3    5  10  10  10  10   5  1   ... 1   3   1   3   1  0  1  42  6
2 2  3   0    5  10   3   7  10  10  2   ... 1   4   1   4   1  1  1  32  5.8
3 3  4   6   10  10  10  10  10  10  1   ... 1   5   2   5   1  1  1  43  1
4 4  4   7    7  10  10   7  10   9  2   ... 1   3   1   4   1  0  1  26  3
5 5  5   2   10  10   9   9   9  10  1   ... 2   3   2   4   1  1  1  37  14
6 6  6   5    8   8   7   7  10   7  1   ... 1   3   1   3   1  0  1  35  8
  JP
1 5
2 4
3 5
4 5
5 5
6 4